#!/usr/bin/env bash
#configuere a new ubuntu machine respecting the requirements
apt-get update
apt-get -y install nginx
chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
