#!/usr/bin/env bash
#configuere a new ubuntu machine respecting the requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
