#!/usr/bin/env bash
#configure a new Ubuntu server to redirect to another page
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ parameter;' /etc/nginx/sites-available/default
sudo service nginx restart
