#!/usr/bin/env bash
# Configure HA proxy to send a traffic web-01 and web-02
sudo apt-get update -y
sudo apt-get install haproxy=1.6.\* -y
sudo chown -R $USER:$USER /etc/haproxy/
echo "frontend my_frontend
	bind *:80
	mode http
	stats uri /haproxy?stats
	default_backend my_backend" >> /etc/haproxy/haproxy.cfg
echo "backend my_backend
	balance roundrobin
	server 459031-web-01 54.234.100.112 check
	server 459031-web-02 3.94.211.28 check " >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
